# Generated by Django 4.1.7 on 2023-03-12 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_unidadpotencia_soportes_otros'),
    ]

    operations = [
        migrations.CreateModel(
            name='kits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='kits')),
                ('battery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.battery')),
                ('otros', models.ManyToManyField(to='products.otros')),
                ('panels', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.solarpanel')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products')),
                ('reguladores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.reguladores')),
            ],
        ),
    ]
