# Generated by Django 4.1.7 on 2023-03-13 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_kits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kits',
            name='description',
        ),
        migrations.RemoveField(
            model_name='kits',
            name='image',
        ),
        migrations.RemoveField(
            model_name='kits',
            name='price',
        ),
    ]
