# Generated by Django 4.1.7 on 2023-03-22 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_kits_numerobattery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voltage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voltage', models.IntegerField()),
            ],
        ),
    ]
