# Generated by Django 4.1.7 on 2023-03-22 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_voltage'),
    ]

    operations = [
        migrations.AddField(
            model_name='battery',
            name='voltage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.voltage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='voltage',
            field=models.ManyToManyField(to='products.voltage'),
        ),
        migrations.AddField(
            model_name='solarpanel',
            name='voltage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.voltage'),
            preserve_default=False,
        ),
    ]
