# Generated by Django 4.0.6 on 2023-03-30 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_battery_voltage_products_voltage_solarpanel_voltage'),
    ]

    operations = [
        migrations.CreateModel(
            name='cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_panels', models.IntegerField()),
                ('cantidad_baterias', models.IntegerField()),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products')),
                ('bateria_adecuada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.battery')),
                ('panel_adecuado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.solarpanel')),
            ],
        ),
    ]
