# Generated by Django 4.1.7 on 2023-03-30 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_kits_battery_remove_kits_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kits',
            name='baterry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.battery'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kits',
            name='batteryAmount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
