# Generated by Django 4.1.7 on 2023-03-30 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_kits_baterry_kits_batteryamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battery',
            name='image',
            field=models.ImageField(null=True, upload_to='Battery'),
        ),
    ]
