# Generated by Django 4.1.7 on 2023-03-30 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_battery_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Battery'),
        ),
    ]
