# Generated by Django 4.1.7 on 2023-03-30 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_battery_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kits',
            old_name='baterry',
            new_name='battery',
        ),
    ]
