# Generated by Django 4.1.7 on 2023-03-30 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_rename_baterry_kits_battery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kits',
            old_name='batteryAmount',
            new_name='battery_amount',
        ),
    ]
