# Generated by Django 4.1.7 on 2023-03-31 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_rename_batteryamount_kits_battery_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kits',
            old_name='panelAmount',
            new_name='panel_amount',
        ),
    ]
