# Generated by Django 4.1.7 on 2023-04-04 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_cotizacion'),
        ('products', '0014_rename_panelamount_kits_panel_amount'),
    ]

    operations = [
    ]
