# Generated by Django 4.1.7 on 2023-04-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_merge_20230404_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reguladores',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reguladores',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Reguladores'),
        ),
        migrations.AlterField(
            model_name='solarpanel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Solar-panel'),
        ),
        migrations.DeleteModel(
            name='cotizacion',
        ),
    ]
