# Generated by Django 4.1.7 on 2023-04-05 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_category_image_breakes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Breakes',
            new_name='Breakers',
        ),
    ]
