# Generated by Django 4.1.7 on 2023-04-05 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_rename_breakes_breakers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakers',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
