# Generated by Django 4.1.7 on 2023-04-24 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_electricmaterials'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeKits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panel_amount', models.IntegerField()),
                ('battery_amount', models.IntegerField()),
                ('battery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.battery')),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.solarpanel')),
                ('product', models.ManyToManyField(to='products.products')),
            ],
        ),
    ]
