# Generated by Django 4.1.7 on 2023-04-25 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_homekits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homekits',
            name='product',
        ),
        migrations.AddField(
            model_name='homekits',
            name='name',
            field=models.CharField(default='NO NAMED KIT', max_length=25, verbose_name='KIT-SOLAR---CODEN'),
        ),
        migrations.CreateModel(
            name='HomeKits_Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.homekits')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products')),
            ],
        ),
    ]
