# Generated by Django 4.1.7 on 2023-04-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_remove_homekits_product_homekits_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubberizedcables',
            name='supported_amperage',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='homekits',
            name='name',
            field=models.CharField(default='KIT - SOLAR---CODEN', max_length=25),
        ),
        migrations.AlterField(
            model_name='homekits_products',
            name='amount',
            field=models.IntegerField(default=1),
        ),
    ]
