# Generated by Django 4.1.7 on 2023-04-27 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_rubberizedcables_supported_amperage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubberizedcables',
            name='supported_amperage',
            field=models.IntegerField(),
        ),
    ]
