# Generated by Django 4.1.7 on 2023-04-27 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_alter_rubberizedcables_supported_amperage'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclecables',
            name='supported_amperage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
