# Generated by Django 4.1.7 on 2023-04-29 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_vehiclecables_supported_amperage'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitypower',
            name='max_ampers_supported',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
