# Generated by Django 4.1.7 on 2023-04-29 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0037_unitypower_max_ampers_supported'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitypower',
            name='battery_kids_supported',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='unity_powers_battery_kids', to='products.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='unitypower',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unity_powers', to='products.category'),
        ),
    ]
