# Generated by Django 4.2 on 2023-05-20 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0039_category_perdida_unitypower_min_ampers_supported'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homekits_products',
            name='kit',
        ),
        migrations.RemoveField(
            model_name='homekits_products',
            name='product',
        ),
        migrations.RemoveField(
            model_name='kits',
            name='battery',
        ),
        migrations.RemoveField(
            model_name='kits',
            name='panel',
        ),
        migrations.RemoveField(
            model_name='kits',
            name='product',
        ),
        migrations.DeleteModel(
            name='HomeKits',
        ),
        migrations.DeleteModel(
            name='HomeKits_Products',
        ),
        migrations.DeleteModel(
            name='kits',
        ),
    ]
