# Generated by Django 4.2 on 2023-05-20 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0040_remove_homekits_products_kit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitHogar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('panel_cantidad', models.IntegerField(blank=True, null=True)),
                ('bateria_cantidad', models.IntegerField(blank=True, null=True)),
                ('breakers_cantidad', models.IntegerField(blank=True, default=3, null=True)),
                ('cable_cantidad', models.IntegerField(blank=True, default=10, null=True)),
                ('cablevehicular_cantidad', models.IntegerField(blank=True, default=10, null=True)),
                ('panel_suport_cantidad', models.IntegerField(blank=True, null=True)),
                ('conectores_cantidad', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/KitHogar')),
                ('bateria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kit_hogar', to='products.battery')),
                ('breakers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kit_hogar', to='products.breakers')),
                ('cable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kit_hogar', to='products.rubberizedcables')),
                ('cable_vehicular', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kit_hogar', to='products.vehiclecables')),
                ('conectores', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kit_hogar', to='products.connectors')),
                ('inversor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kit_hogar', to='products.inversores')),
                ('material_electrico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kit_hogar', to='products.electricmaterials')),
                ('modulo_centralizado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kit_hogar', to='products.centralizedmodule')),
                ('panel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kit_hogar', to='products.solarpanel')),
                ('panel_suport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kit_hogar', to='products.panelsupports')),
                ('productos', models.ManyToManyField(related_name='kit_hogar', to='products.products')),
                ('puesta_tierra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kit_hogar', to='products.groundsecuritykits')),
                ('regulador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kit_hogar', to='products.reguladores')),
                ('terminales', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kit_hogar', to='products.terminals')),
                ('unidad_de_potencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kit_hogar', to='products.unitypower')),
            ],
        ),
    ]
