# Generated by Django 4.2 on 2023-06-26 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0042_showcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='showcategory',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
